### ISSUE TITLE
Should default implementations be kept out of this module?

### ISSUE THREAD

**Issue by Chat-Wane** [justayak/network#1]
Currently, when you import network has a module, you get the dependency cyclon for the membership, and a default broadcasting. Maybe it should be better to keep network independent of other modules ( even if it does not work as a standalone).

Thus, we have the following modules (or projects):
- simpleBroadcastingDefinition
- cyclon (maybe add membership and rtc in the name somehow ? )
- cyclon (composition of the chosen broadcast and cyclon membership + network as a dependency)

Then, keep the example, or an up-to-date list of modules that implement the interfaces?

**Comment by jutanke** [comment]
We should remove Cyclon from the library. The type of dissemination should be determinate only by the user. I will adapt that asap.

**Comment by Chat-Wane** [comment]
I removed the dependencies and exported your primitive-broadcast into another project ( hope you don't mind ). I think it is more modular now.

Hopefully, it does not break the work you did in the meantime. It shouldn't since the changes are minors.
